require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe PortfolioSitesController do

  # This should return the minimal set of attributes required to create a valid
  # PortfolioSite. As you add validations to PortfolioSite, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # PortfolioSitesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all portfolio_sites as @portfolio_sites" do
      portfolio_site = PortfolioSite.create! valid_attributes
      get :index, {}, valid_session
      assigns(:portfolio_sites).should eq([portfolio_site])
    end
  end

  describe "GET show" do
    it "assigns the requested portfolio_site as @portfolio_site" do
      portfolio_site = PortfolioSite.create! valid_attributes
      get :show, {:id => portfolio_site.to_param}, valid_session
      assigns(:portfolio_site).should eq(portfolio_site)
    end
  end

  describe "GET new" do
    it "assigns a new portfolio_site as @portfolio_site" do
      get :new, {}, valid_session
      assigns(:portfolio_site).should be_a_new(PortfolioSite)
    end
  end

  describe "GET edit" do
    it "assigns the requested portfolio_site as @portfolio_site" do
      portfolio_site = PortfolioSite.create! valid_attributes
      get :edit, {:id => portfolio_site.to_param}, valid_session
      assigns(:portfolio_site).should eq(portfolio_site)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new PortfolioSite" do
        expect {
          post :create, {:portfolio_site => valid_attributes}, valid_session
        }.to change(PortfolioSite, :count).by(1)
      end

      it "assigns a newly created portfolio_site as @portfolio_site" do
        post :create, {:portfolio_site => valid_attributes}, valid_session
        assigns(:portfolio_site).should be_a(PortfolioSite)
        assigns(:portfolio_site).should be_persisted
      end

      it "redirects to the created portfolio_site" do
        post :create, {:portfolio_site => valid_attributes}, valid_session
        response.should redirect_to(PortfolioSite.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved portfolio_site as @portfolio_site" do
        # Trigger the behavior that occurs when invalid params are submitted
        PortfolioSite.any_instance.stub(:save).and_return(false)
        post :create, {:portfolio_site => {}}, valid_session
        assigns(:portfolio_site).should be_a_new(PortfolioSite)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        PortfolioSite.any_instance.stub(:save).and_return(false)
        post :create, {:portfolio_site => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested portfolio_site" do
        portfolio_site = PortfolioSite.create! valid_attributes
        # Assuming there are no other portfolio_sites in the database, this
        # specifies that the PortfolioSite created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        PortfolioSite.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => portfolio_site.to_param, :portfolio_site => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested portfolio_site as @portfolio_site" do
        portfolio_site = PortfolioSite.create! valid_attributes
        put :update, {:id => portfolio_site.to_param, :portfolio_site => valid_attributes}, valid_session
        assigns(:portfolio_site).should eq(portfolio_site)
      end

      it "redirects to the portfolio_site" do
        portfolio_site = PortfolioSite.create! valid_attributes
        put :update, {:id => portfolio_site.to_param, :portfolio_site => valid_attributes}, valid_session
        response.should redirect_to(portfolio_site)
      end
    end

    describe "with invalid params" do
      it "assigns the portfolio_site as @portfolio_site" do
        portfolio_site = PortfolioSite.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        PortfolioSite.any_instance.stub(:save).and_return(false)
        put :update, {:id => portfolio_site.to_param, :portfolio_site => {}}, valid_session
        assigns(:portfolio_site).should eq(portfolio_site)
      end

      it "re-renders the 'edit' template" do
        portfolio_site = PortfolioSite.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        PortfolioSite.any_instance.stub(:save).and_return(false)
        put :update, {:id => portfolio_site.to_param, :portfolio_site => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested portfolio_site" do
      portfolio_site = PortfolioSite.create! valid_attributes
      expect {
        delete :destroy, {:id => portfolio_site.to_param}, valid_session
      }.to change(PortfolioSite, :count).by(-1)
    end

    it "redirects to the portfolio_sites list" do
      portfolio_site = PortfolioSite.create! valid_attributes
      delete :destroy, {:id => portfolio_site.to_param}, valid_session
      response.should redirect_to(portfolio_sites_url)
    end
  end

end
